version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "craft-demo"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-6x46n5ybgopw"
s3_prefix = "craft-demo"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
