AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  craft-demo
  Sample SAM Template for craft-demo
Globals:
  Function:
    Timeout: 3

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: python3.7
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /hello
            Method: get

  PatientMedScheduleFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: patient_med_schedule/
      Handler: app.lambda_handler
      Runtime: python3.7
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref PatientTable
      Events:
        PatientMedSchedule:
          Type: Api
          Properties:
            Path: /schedule
            Method: post

  PatientTable:
    Type: AWS::DynamoDB::Table
    Properties: 
      AttributeDefinitions: 
        - AttributeName: patientId
          AttributeType: S
      KeySchema: 
        - AttributeName: patientId
          KeyType: HASH
      ProvisionedThroughput: 
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

Outputs:
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
  PatientMedScheduleFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt PatientMedScheduleFunction.Arn
  PatientMedScheduleFunction:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt PatientMedScheduleFunctionRole.Arn
