AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  craft-demo
  Sample SAM Template for craft-demo
Globals:
  Function:
    Timeout: 3

Resources:
  PatientMedScheduleFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: patient_med_schedule/
      Handler: app.lambda_handler
      Runtime: python3.7
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref PatientTable
      Events:
        PatientMedSchedule:
          Type: Api
          Properties:
            Path: /schedule
            Method: post
        PatientMedSchedulePut:
          Type: Api
          Properties:
            Path: /schedule/{Id}
            Method: put
        PatientMedScheduleGet:
          Type: Api
          Properties:
            Path: /schedule/{Id}
            Method: get
        PatientMedScheduleDelete:
          Type: Api
          Properties:
            Path: /schedule/{Id}
            Method: delete


  PatientTable:
    Type: AWS::DynamoDB::Table
    Properties: 
      TableName: PatientTable
      AttributeDefinitions: 
        - AttributeName: patientId
          AttributeType: S
      KeySchema: 
        - AttributeName: patientId
          KeyType: HASH
      ProvisionedThroughput: 
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

Outputs:
  PatientMedScheduleApi:
    Description: "API Gateway endpoint URL for Prod stage for patient schedule function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/schedule/"
  PatientMedScheduleFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt PatientMedScheduleFunction.Arn
  PatientMedScheduleFunctionIamRole:
    Description: "Implicit IAM Role created for patient function"
    Value: !GetAtt PatientMedScheduleFunctionRole.Arn
